### ISSUE TITLE
Why Enricher.ClientInfo?

### ISSUE THREAD

**Issue by mivandoni** [denis-peshkov/Serilog.Enrichers.HttpContext#3]
In using section you add "Serilog.Enrichers.ClientInfo" but when I load the applicaction it says Could not load file or assembly 'Serilog.Enrichers.ClientInfo, Culture=neutral, PublicKeyToken=null'. 
Do I need to add this enricher too?

**Comment by UrsKroell** [comment]
That's an error in the documentation.
The correct line is:

`"Using":  [ "Serilog.Enrichers.HttpContext" ],`
